baseURL = "https://rohbomb.github.io/"
# GitHub Actions Build Trigger
languageCode = "ko-kr"
title = "Global Market Insights"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = true # Bot(KST) vs Server(UTC) Timezone Issue Fix
buildExpired = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  env = "production"
  title = "Global Market Insights"
  description = "In-depth Market Analysis & Tech Trends"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "Analyst Bear"
  # images = ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat = "2006-01-02"
  defaultTheme = "dark" # dark, light
  disableThemeToggle = true

  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  ShowRelatedContent = true

  [params.profileMode]
    enabled = false
    title = "Global Market Insights"
    subtitle = "In-depth Market Analysis & Tech Trends"
    imageUrl = "<link or path of image for opengraph, twitter-cards>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"
    buttons = [
      { name = "Posts", url = "posts" },
      { name = "Tags", url = "tags" }
    ]

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/rohbomb"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
