baseURL = "https://rohbomb.github.io/"
languageCode = "ko-kr"
title = "My Hybrid Cash Cow"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = "production"
  title = "My Hybrid Cash Cow"
  description = "IT/과학 뉴스와 인사이트"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "Rohbomb"
  # images = ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat = "2006-01-02"
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

  [params.profileMode]
    enabled = false
    title = "My Hybrid Cash Cow"
    subtitle = "IT/과학 뉴스와 인사이트"
    imageUrl = "<link or path of image for opengraph, twitter-cards>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"
    buttons = [
      { name = "Posts", url = "posts" },
      { name = "Tags", url = "tags" }
    ]

<<<<<<< HEAD
  [params.socialIcons]
    Github = "https://github.com/rohbomb"
=======
#   [[params.socialIcons]]
#     name = "Github"
#     url = "https://github.com/rohbomb"
>>>>>>> c9a1f1de68f507f0b954d886e0fc92be5499f664

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
