baseURL = "https://rohbomb.github.io/"
languageCode = "ko-kr"
title = "My Hybrid Cash Cow"
theme = "blowfish"


[params]
  colorScheme = "blowfish"
  defaultTheme = "light"
  enableSearch = true
  
  [params.header]
    layout = "fixed"

  [params.footer]
    showCopyright = true

  [params.homepage]
    layout = "background"
    showRecent = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
